### ISSUE TITLE
[BUG] Error when trying to export/import on iOS device

### ISSUE THREAD

**Issue by weldonsouza** [JaffaKetchup/flutter_map_tile_caching#155] opened 2024-05-10 14:55 UTC
### What is the bug?

When trying to use the export/import functions
final importResult = FMTCRoot.external(pathToArchive: pathController.text).import(strategy: selectedConflictStrategy);
or
await FMTCRoot.external(pathToArchive: pathController.text).export(storeNames: selectedStores.toList());
on iOS device results in this error

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: StorageException: failed to create store: Could not open database environment; please check options and file system (1: Operation not permitted) (OBX_ERROR code 10199)
#0      ObjectBoxNativeError.throwMapped (package:objectbox/src/native/bindings/helpers.dart:99:11)
#1      throwLatestNativeError (package:objectbox/src/native/bindings/helpers.dart:54:48)
#2      checkObxPtr (package:objectbox/src/native/bindings/helpers.dart:31:5)
#3      Store._checkStorePointer (package:objectbox/src/native/store.dart:439:7)
#4      new Store (package:objectbox/src/native/store.dart:262:7)
#5      _worker.mainHandler (package:flutter_map_tile_caching/src/backend/impls/objectbox/backend/internal_workers/standard/worker.dart:761:31)
#6      _worker.<anonymous closure> (package:flutter_map_tile_caching/src/backend/impls/objectbox/backend/internal_workers/standard/worker.dart:1327:7)
#7      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#11     _StreamController._add (dart:async/stream_controller.dart:658:7)
#12     _StreamController.add (dart:async/stream_controller.dart:606:5)
#13     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
<asynchronous suspension>
#0      _ObjectBoxBackendImpl._sendCmdOneShot (package:flutter_map_tile_caching/src/backend/impls/objectbox/backend/internal.dart:58:63)
<asynchronous suspension>
#1      _ObjectBoxBackendImpl.exportStores (package:flutter_map_tile_caching/src/backend/impls/objectbox/backend/internal.dart:570:5)
<asynchronous suspension>
#2      SettingController.exportStoreTiles (package:appgestor/shared/controllers/setting_controller.dart:335:7)
<asynchronous suspension>
#+      [FMTC Debug Info]      _CmdType.exportStores: {storeNames: [test_map], outputPath: /private/var/mobile/Containers/Shared/AppGroup/3EFA1129-48AF-4593-AB20-28331DDD905F/File Provider Storage/Comdecs iOS/test_map.fmtc}
```

### How can we reproduce it?

Using the example application, it was already possible to reproduce the error when trying to export or import only on an iOS device

### Platforms

iOS (device used iPhone 13 version 17.3.1)

### Severity

Fatal: Causes the application to crash

**Comment by JaffaKetchup** [comment] 2024-05-10 15:10
Hi @weldonsouza,
Thanks for reporting an issue.

I'm not aware of exactly how it works on iOS, but it would appear that maybe the app doesn't have permission to write to the specified directory:
> Could not open database environment; please check options and file system (1: Operation not permitted) (OBX_ERROR code 10199)

And the output path you've specified looks very similar to the one in [this Reddit post](https://www.reddit.com/r/flutterhelp/comments/11yx2nh/ios_cannot_save_file_using_file_picker_for_path/), where they had to switch to using a different directory:
> outputPath: /private/var/mobile/Containers/Shared/AppGroup/3EFA1129-48AF-4593-AB20-28331DDD905F/File Provider Storage/Comdecs iOS/test_map.fmtc

Can you please try specifying a directory you can ensure you have access to? Try using 'dart:io' to create a file there yourself before calling FMTC.

---

<sub>*Please note that FMTC is licensed under GPL v3. If you're developing an application that isn't licensed under GPL, this affects you and your application's legal right to distribution. Please see https://fmtc.jaffaketchup.dev/proprietary-licensing, or get in touch, for more information.*</sub>

**Comment by weldonsouza** [comment] 2024-05-10 15:20
Thanks for the quick response, I'll try your tip, when I get some results I'll make it available, it might help someone in the future.

**Comment by weldonsouza** [comment] 2024-05-10 19:31
After several attempts, the error is not the location where it is saved, but rather a conflict with the objectBox, my current application uses objectBox
```
Bad state: failed to create store: Cannot open store: another store is still open using the same path: "/private/var/mobile/Containers/Data/Application/9809AC8D-8133-4A56-9999-1232960F0FE7/Documents" (OBX_ERROR code 10001)
```
I even did a test by closing the objectBox before calling the export/import function, but it results in another error
```
ObjectBoxException: failed to create store: DB's last entity ID 30 is higher than 4 from model
```
If you have any solution I would appreciate it.

**Comment by JaffaKetchup** [comment] 2024-05-11 14:16
Try exporting to a new subdirectory, so that the 'data.mdb' files don't conflict.

**Comment by weldonsouza** [comment] 2024-05-13 16:56
I had already tried your suggestion before, passing some logs to better illustrate (this is only happening on the physical iOS device):

Export function, if you use it the way it is in the example, you will get this error
```
StorageException: failed to create store: Could not open database environment; please check options and file system (1: Operation not permitted) (OBX_ERROR code 10199)
```
Creating a subdirectory
```
PathAccessException: Creation failed, path = '/private/var/mobile/Containers/Shared/AppGroup/3EFA1129-48AF-4593-AB20-28331DDD905F/File Provider Storage/Comdecs iOS/mySubDirectory' (OS Error: Operation not permitted, errno = 1)
```

Using path_provider
```
StorageException: failed to create store: Could not open database environment; please check options and file system (1: Operation not permitted) (OBX_ERROR code 10199)
```

Creating a subdirectory (path_provider)
```
PathAccessException: Creation failed, path = '/private/var/mobile/Containers/Shared/AppGroup/3EFA1129-48AF-4593-AB20-28331DDD905F/File Provider Storage/Comdecs iOS/mySubDirectory' (OS Error: Operation not permitted, errno = 1)
```

Import function
When testing on the app it simply crashes and closes (I also exported the android file to test). The only error in the log I could get was this
```
DartWorker (93): EXC_BAD_ACCESS (code=1, address=0x113d67010)
```

**Comment by JaffaKetchup** [comment] 2024-05-13 17:35
If you can't create a subdirectory because you don't have permission, then it's unlikely it's a fault with FMTC. Try using 'path_provider's `getApplicationDocumentsDirectory()` method, with a subdirectory. If it works here, then it's not a bug with FMTC, and you would need to choose another directory.

**Comment by weldonsouza** [comment] 2024-05-13 17:44
I already tested using getApplicationDocumentsDirectory() the result is the same
```
StorageException: failed to create store: Could not open database environment; please check options and file system (1: Operation not permitted) (OBX_ERROR code 10199)
```

Creating a subdirectory (path_provider)
```
PathAccessException: Creation failed, path = '/private/var/mobile/Containers/Shared/AppGroup/3EFA1129-48AF-4593-AB20-28331DDD905F/File Provider Storage/Comdecs iOS/mySubDirectory' (OS Error: Operation not permitted, errno = 1)
```

**Comment by JaffaKetchup** [comment] 2024-05-13 17:51
If you can't create a subdirectory/file, ObjectBox can't create a file.

If FMTC works normally otherwise, it must be able to create a file somwhere. This is how FMTC does it:

```dart
await Directory(
	this.rootDirectory = path.join(
		rootDirectory ?? (await getApplicationDocumentsDirectory()).absolute.path,
		'fmtc',
	),
).create(recursive: true);
```

Try replacing 'fmtc' with something else.

But at the moment, it doesn't look like an FMTC issue - the only thing I can think of, if they are indeed the same directory, is that FMTC is locking the subdirectory.

**Comment by JaffaKetchup** [comment] 2024-05-21 10:04
I'm closing this for now, as I'm not certain FMTC's at fault here. Feel free to ping me if you still have more questions!

**Closed by JaffaKetchup** 2024-05-21 10:04 UTC
Labels: bug, needs verification
