### ISSUE TITLE
Example and plugin issue on ios 

### ISSUE THREAD

**Issue by romreed** [JaffaKetchup/flutter_map_tile_caching#47] opened 2022-03-04 16:02 UTC
Unsupported operation: Watching is not supported on the current platform
iphone x 15.3.1
flutter 2.10.0

![image](https://user-images.githubusercontent.com/16118227/156797216-47851955-4223-457a-b7d9-455c031cd194.png)

**Comment by JaffaKetchup** [comment] 2022-03-04 16:05
Duplicate of #43. Please look through closed issues before posting a new one: an answer may already be provided.

**Comment by JaffaKetchup** [comment] 2022-03-04 16:39
Did that answer your question? Please let me know if you have any others!

**Comment by romreed** [comment] 2022-03-04 16:43
@JaffaKetchup it's flutter issue. Thank you for your answer.

**Closed** 2022-03-04 16:44 UTC
Labels: bug, duplicate
