### ISSUE TITLE
[BUG] Example app on Windows desktop throws when starting download

### ISSUE THREAD

**Issue by pamtbaau** [JaffaKetchup/flutter_map_tile_caching#63] opened 2022-08-04 08:17 UTC
**Describe The Bug**
When running the example app on Windows desktop, an exception is thrown when clicking the arrow to start the download. No window appears to set the download settings and choosing to download in foreground.

> PlatformException (PlatformException(notAndroid, The background download feature is only available on Android due to internal limitations., null, null))

**Expected Behaviour**
I would expect the download settings page to appear and being able to download in foreground.

**Screenshots & Recordings**
If possible, add screenshots or recordings to help explain your problem. This can quickly improve diagnosis of the issue.

**Additional Information**
Add any other context about the problem here, or remove this section.

---

**Doctors Report**

```shell
Paste your report from `flutter doctor` inside here
```

**To Reproduce**
Steps to reproduce the behaviour:

1. Open app in Windows desktop
2. Open download
3. Select region
4. Hit arrow button to open download page
5. Exception thrown...
---

**Severity**
This will help us to label the issue quicker and decide what needs attention first. Only choose fatal if the entire app crashes, otherwise choose non-fatal.

- [ ] Non-Fatal
- [ x] Fatal / App Crashes

**Frequency/Rarity**
This will help us to label the issue quicker and decide what needs attention first.

- [ ] Once
- [ ] Uncommon
- [ ] Common
- [ x] Always

**Applicable Platforms**
Only select those that you've tested on - one or more. If possible, test on a variety of platforms.

- [ ] Android
- [ ] iOS
- [ ] Web
- [ x] Windows
- [ ] Others (beta platforms)

**Comment by JaffaKetchup** [comment] 2022-08-04 08:21
Hi there. I can't seem to reproduce this issue using the latest codebase. Can you build the example app, run it and make sure it errors for you, then send it to me as a .zip? Many thanks.

**Comment by pamtbaau** [comment] 2022-08-04 09:57
Zip  is too big to upload... 156 MB

**Comment by JaffaKetchup** [comment] 2022-08-04 10:12
It should only be about 10MB. Can you try this one: https://github.com/JaffaKetchup/flutter_map_tile_caching/blob/main/prebuiltExampleApplications/WindowsApplication.zip. Its been built from the latest code.

**Comment by pamtbaau** [comment] 2022-08-04 10:22
I've zipped the entire example folder. Did you perhaps meant a zip of a subfolder?

I've tried running the example.exe from the prebuild windows version. It does show the download settings page, but Start download in: Foreground doesn't do anything.

**Comment by JaffaKetchup** [comment] 2022-08-04 10:24
Yeah, I just meant zipping the output. For me, the application works as expected:
![image](https://user-images.githubusercontent.com/58115698/182824989-b3ccb934-8437-4818-9a1e-df749cf1d86d.png)

**Comment by pamtbaau** [comment] 2022-08-04 10:26
Where "output" means which folder?

**Comment by JaffaKetchup** [comment] 2022-08-04 10:39
Can you screen record yourself using the application? I'm struggling to reproduce this.

**Comment by JaffaKetchup** [comment] 2022-08-04 10:42
Also, sending the current 'fmtc' directory on your machine that causes the error might help me reproduce it.

**Comment by pamtbaau** [comment] 2022-08-04 10:46
Please treat me as a 5 year old... 'fmtc' directory??? Do you mean AppData/Roaming/dev.org.fmtc.example ?

[dev.org.fmtc.example.zip](https://github.com/JaffaKetchup/flutter_map_tile_caching/files/9258993/dev.org.fmtc.example.zip)

**Comment by JaffaKetchup** [comment] 2022-08-04 10:57
There should be an 'fmtc' directory in your Documents folder AFAIK.

**Comment by pamtbaau** [comment] 2022-08-04 10:59
[fmtc.zip](https://github.com/JaffaKetchup/flutter_map_tile_caching/files/9259068/fmtc.zip)

**Comment by JaffaKetchup** [comment] 2022-08-04 11:00
Ok, let me test that directory, thanks.

**Comment by pamtbaau** [comment] 2022-08-04 11:01
Not sure what information a screen record will provide. Are you looking for something specific?

**Comment by JaffaKetchup** [comment] 2022-08-04 11:02
Ah not to worry, I've found an issue now I've got that. Give me a minute or two to debug.

**Comment by JaffaKetchup** [comment] 2022-08-04 11:10
Ah, I think I've found your issue. You seem to have migrated from v4, so there are some missing required files in the store.
There is an issue internally, so I'll try to get that resolved. The best way for you to fix the issue for now is to completely delete 'Default Store' and create a new one.

**Comment by pamtbaau** [comment] 2022-08-04 11:13
Today, I've multiple times deleted the entire folder, cloned the repo, cd-ed to example folder and build it... No migration...

**Comment by JaffaKetchup** [comment] 2022-08-04 11:15
Hmm, that's strange. I'll send you over my 'fmtc' directory, can you see if it works. My computer just BSODed so I'll send it in a minute.

**Comment by JaffaKetchup** [comment] 2022-08-04 11:17
[fmtc.zip](https://github.com/JaffaKetchup/flutter_map_tile_caching/files/9259175/fmtc.zip)
Here you go. Just replace the existing 'fmtc' directory and see if it works. Just seen your edit, the fmtc folder is the most important part.

**Comment by pamtbaau** [comment] 2022-08-04 11:32
Deleted the fmtc folder and rebuild the app.

- In Release mode, download starts
- In Debug mode, same exception as thrown before by 'download.dart' line 339. Replaced it with `return false` and download starts.

**Comment by JaffaKetchup** [comment] 2022-08-04 11:38
Ah I can see why this happens. It's not an issue. It throws, but is safely caught by the example application. If using VS Code, try using 'Run Without Debugging'. This only shows errors if they are not caught.

**Comment by JaffaKetchup** [comment] 2022-08-04 11:41
As the issue is only within the example application here, I'm going to close this. Thanks for reporting it!

**Comment by JaffaKetchup** [comment] 2022-08-04 11:41
I'm happy to help more if you need it.

**Closed by JaffaKetchup** 2022-08-04 11:41 UTC
Labels: bug

**Comment by pamtbaau** [comment] 2022-08-04 11:49
Uhh... I don't think that the "workaround" by running in Release mode is a proper way to go... This will have people run into issues like I did. It should not happen.

**Comment by JaffaKetchup** [comment] 2022-08-04 11:55
This will only happen in the example application after a migration from a v4 format. It is not an issue in the library itself.

**Comment by pamtbaau** [comment] 2022-08-04 11:58
I'm sorry to say, but it happens on a fresh clone with a deleted fmtc folder. No migration from v4.

**Comment by JaffaKetchup** [comment] 2022-08-04 11:59
Which error?

**Comment by pamtbaau** [comment] 2022-08-04 12:01
'download.dart' line 339
> Exception has occurred.
PlatformException (PlatformException(notAndroid, The background download feature is only available on Android due to internal limitations., null, null))

**Comment by JaffaKetchup** [comment] 2022-08-04 12:02
Yes, this is not an error to worry about. This is thrown by my library correctly, and the example application catches it correctly - I've checked the code and other bits. If it errors in release, then that is an issue, but it doesn't: meaning it is caught and handled correctly.

**Comment by pamtbaau** [comment] 2022-08-04 12:13
Well, in my perception it is not OK if an Exception causes the IDE to hit a breakpoint because it has not been handled correctly. 

I'm using a default VSCode build and debug setting for Dart/Flutter and have hit the issue leading to this discussion. I'm not sure if it's OK to have others hit the issue too. 

If you're not willing to fix it, that's your prerogative, but it should at least be documented that the example will break.

**Comment by pamtbaau** [comment] 2022-08-04 12:19
Apart from what has been said above, I highly respect what your have created with this plugin!

**Comment by JaffaKetchup** [comment] 2022-08-04 12:22
VSCode will do this:
![image](https://user-images.githubusercontent.com/58115698/182844740-4d13117f-5e63-4f10-81cc-07f65bc4ffd6.png)
If any exception occurs, handled or not. In this case, it is handled by this code:
![image](https://user-images.githubusercontent.com/58115698/182844965-10e303fe-d125-48f3-a230-074ade0f6e90.png)
...located in the example application.

I'm not sure what you want me to say. I cannot fix this issue: it is not an issue. I can add a platform check to the example application, but this adds unnecessary complexity for something that the library already does for me.

As I said above, try running it with 'Run Without Debugging'/Ctrl+F5 as opposed to 'Start Debugging'/F5. In this mode, there is only an issue if it appears in the console, which you can see it does not:
![image](https://user-images.githubusercontent.com/58115698/182845764-f84e6e09-08f9-483a-9f2a-cf218043f1b6.png)


Thanks for your interest in this plugin, it really means a lot to me that it can be used in any useful way :)
