### ISSUE TITLE
Ability to cache multiple tile sets (same coordinates but different style)

### ISSUE THREAD

**Issue by bmason8** [JaffaKetchup/flutter_map_tile_caching#10] opened 2021-06-21 16:25 UTC
I have a button for toggling between two distinct map styles (street and satellite). However, because of the (awesome) map caching when I switch styles the map layer will stay the same because it's already been cached (which is the correct and expected behaviour). Would it be possible to add a parameter to the `TileLayerOptions` that allowed for additional caches (like a subfolder) so if there was a value passed in it would store/retrieve the tiles to/from that "sub cache". And if you didn't need this functionality the parameter could just be left empty and it would default to the main cache.

My current solution is to use the `NonCachingNetworkTileProvider` whenever the user toggles for the second style (satellite in my case) which works fine but obviously if they end up using that style primarily they lose out on the tile caching benefits.

I suspect I won't be the only person with this issue and if there is a better way of doing this then please suggest it!

**Comment by JaffaKetchup** [comment] 2021-06-21 16:26
Great point! I'll see what I can do, I should be back soon.

**Comment by JaffaKetchup** [comment] 2021-06-21 16:32
Ok, that was quicker than I expected. See these two lines of code sets all the values for table and file name:
```
static final String _kDbName = 'tile_cach.db';
static final String _kTilesTable = 'tiles';
```
Theoretically, if I allow these too be changed, that should allow separate caches. It may take me a while to get back through the code and make these values changeable? but I'll see what I can do.

Due to this being high priority, I won't wait for the next release, and I'll release this as v2.1.0 hopefully within 72 hours.

Thanks for reporting!

**Comment by bmason8** [comment] 2021-06-21 17:42
Awesome, thank you so much!

**Comment by JaffaKetchup** [comment] 2021-06-22 17:00
You can see how I'm getting along in the multiple-caches branch. Please note, this is not production ready, and is still in development.

**Comment by JaffaKetchup** [comment] 2021-06-23 14:48
Unfortunately, It's unlikely to be ready today, because I've been also working on the other branches and I've had exams this week as well as next, but I'll see what I can do. It would be great help if you could help test it when it's ready?

Also, this will be released as part of v3.0.0 because it is a breaking change. You will be able to use it by branch, however.

**Comment by bmason8** [comment] 2021-06-23 16:01
No problem at all, I understand and appreciate the effort! Yeah I can definitely help test it when it's ready.

**Comment by JaffaKetchup** [comment] 2021-06-27 12:19
I think we're almost there!

**Comment by JaffaKetchup** [comment] 2021-06-27 16:46
Hmm, this is proving to be quite difficult. If you have the time to spare, some help (a PR on the v3 branch) would be greatly appreciated to get this release done soon!

**Comment by bmason8** [comment] 2021-06-28 16:55
@JaffaKetchup I can't take a look until tomorrow but I'm happy to then. Is there anything in particular you want me to look at? Do you need me to test it out and find bugs or is it not functional yet? I'm new to contributing so any guidance would be super helpful. Thanks!

**Comment by JaffaKetchup** [comment] 2021-06-28 17:54
Sure that's alright, I took at least that long 😂. So the issue is I'm struggling to get the caches to split. That 'table name' variable I mentioned I think could be a way to do it. Alternatively, (and I might have a go at this?) it may be possible to store an 'identifier' along with each tile entry and look at that every time a table is written or read. Most of the stuff you'll need to change is in the tile manager file but you'll probably need to change stuff in the storage manager file. Please make sure to do it in the V3 branch.
Guidelines are to maintain the style of code I've written throughout (indentation, correct spelling, useful comments etc.), and do what you think is good. Mainly, however, don't stress about it, if you can't do it that's fine, I'll keep trying (I will anyway!). Thanks!

**Comment by JaffaKetchup** [comment] 2021-06-29 16:29
Actually, don't worry about it at all! I think I have figured it out...
Thanks anyways :)!

**Comment by bmason8** [comment] 2021-06-29 18:18
Haha ok awesome! And thanks for the information regardless!

**Comment by JaffaKetchup** [comment] 2021-06-30 18:57
https://github.com/JaffaKetchup/flutter_map_tile_caching/pull/11#issuecomment-871649834
Due to this, this issue is being closed.
Thanks a bunch 👍 :) !

**Closed by JaffaKetchup** 2021-06-30 18:57 UTC
Labels: enhancement, high priority

**Comment by JaffaKetchup** [comment] 2021-07-01 20:29
https://github.com/JaffaKetchup/flutter_map_tile_caching/pull/11#issuecomment-872529909
