### ISSUE TITLE
[BUG] Latest commit v4: Bulk Downloading Example Not Working

### ISSUE THREAD

**Issue by take2make** [JaffaKetchup/flutter_map_tile_caching#35] opened 2021-12-22 15:26 UTC
The download region is not working. I expected that after downloading the region I can observe it during offline mode.

**Comment by JaffaKetchup** [comment] 2021-12-22 15:31
Hi there,
This seems a bit odd, it works as far as I know.

Please post your code (using correct formatting), and tell me:

 - How long did the download supposedly take?
 - How many tiles does it say you have in your store?
 - Did you receive any `DownloadProgress` events, during the download?

Hope I can help!

**Comment by take2make** [comment] 2021-12-22 15:36
I used the example app.
1. Approximately 5 seconds
2. ~500 tiles
3. During the download in terminal I got loading status in percents. After 100%, I closed the download region mode but the number of tiles did not change and also this region is not available offline.

**Comment by JaffaKetchup** [comment] 2021-12-22 15:38
Is this the v4 or main version?

500 tiles should take a bit more than 5 seconds, but if it's reporting that many tiles, there should be that many tiles.

**Comment by take2make** [comment] 2021-12-22 15:41
in v4, because only this example consists of a working demo

**Comment by JaffaKetchup** [comment] 2021-12-22 15:59
After going back to it, I can confirm that the latest commit does not work. The version on pub.dev is also incomplete. Assuming you are using the latest commit (the only one that you can actually do anything in), it is unclear the reason for this.

I'm looking into it.

**Comment by JaffaKetchup** [comment] 2021-12-24 15:39
Hi there,

I think I have fixed this issue mostly in the latest commit. Note the UI is still incomplete, and being worked on.

Also, the issue that I resolved indicates to me that you were likely using OpenStreetMaps during bulk downloading? If so (please forgive me if I'm wrong), please make sure you are agreeing to the [ToS here](https://operations.osmfoundation.org/policies/tiles/).

Please close this if fixed!
Thanks.

**Comment by take2make** [comment] 2021-12-27 09:30
Great! Now it's working

**Closed** 2021-12-27 09:30 UTC
Labels: bug
