### ISSUE TITLE
[BUG] Cannot open Environment: MdbxError (12): Cannot allocate memory

### ISSUE THREAD

**Issue by frankActivateDesign** [JaffaKetchup/flutter_map_tile_caching#144] opened 2024-01-24 01:05 UTC
### What is the bug?

**"Cannot open Environment: MdbxError (12): Cannot allocate memory"**

On iOS I get IsarError when attempting to import a large (2.65GB) FMTC local file (with `FMTC.instance.rootDirectory.import.manual`)

This error is caught in **fmtc_plus_sharing(v.8.0.0) - import.dart** (line 112) when it attempts to execute `Isar.open` on the imported file. The import fails.

```dart
tmpDb =  await Isar.open(
  [DbStoreDescriptorSchema, DbTileSchema, DbMetadataSchema],
  name: tmpPath.replaceAll('.isar', ''),
  directory: tmpDir.absolute.path,
  maxSizeMiB: FMTC.instance.settings.databaseMaxSize,
  compactOnLaunch:
    FMTC.instance.settings.databaseCompactCondition,
  inspector: FMTC.instance.debugMode,
);
```
Seen on physical iOS 16 regardless of databaseMaxSize value.

On the physical iOS 17.2 and iOS simulators (16.2 and 17.2), have to set databaseMaxSize: 2048, it imports okay but see warnings when the map is loaded on the screen, but is functional.

No issues seen on physical Android devices.

Is this a limitation of iOS systems? Can the FMTC iOS application memory be modified ?

### Here is our implementationHere is our implementation
(fmtc importable file is 2.65gb)

```dart
await FlutterMapTileCaching.initialise(
  settings: FMTCSettings(
  databaseMaxSize: 32768,
  // HAVE TRIED BUT SAME ISSUE WITH ALL: 256, 1024, 2048, 2800, 4096, 8192, ETC
));
...
File f =  '/var/mobile/Containers/Data/Application/552BB35A-E211-4B33-B222-CBA01048908A/Library/Application Support/myMapFile123.fmtc';
var x = FMTC.instance.rootDirectory.import.manual(
  [f],
  collisionHandler: (filename, storeName) => true,
);
```

### How can we reproduce it?

Trying to import a large fmtc file (happening on 2.65GB), presumably anything more than default size of 2048mb.

### Do you have a potential solution?

Increase iOS application memory allocation ?

### Platforms

iOS 16, 17

### Severity

Fatal: Import fails - **successful: false, storeName: null**

**Comment by JaffaKetchup** [comment] 2024-01-24 22:22
Hi @frankActivateDesign,

Unfortunately, this is a known issue with some versions of iOS. Some devices are worse off, your testing device seems to be slightly better off. The import process is quite memory intensive, as it needs to open and close databases multiple times.

I'm currently in the process of migrating to ObjectBox as the storage mechanism in FMTC v9 - but, unfortunately, I don't have an estimated release date yet, and I cannot guarantee that ObjectBox will fair any better.

For more information, please see #105, https://github.com/JaffaKetchup/flutter_map_tile_caching/issues/105#issuecomment-1784227796 and later for updates.

Thanks for trying FMTC, and I hope that v9 resolves this issue for you!

Marking as duplicate of #105.

**Closed by JaffaKetchup** 2024-01-24 22:22 UTC
Labels: bug, needs verification

**Comment by frankActivateDesign** [comment] 2024-01-24 22:58
Hi @JaffaKetchup , thanks for quick reply. 
FMTC is great, I love it.

I have actually found a fix !

In xCode, if you add the 'Extended Virtual Addressing' and 'Increased Memory Limit' entitlements - Capability (Targets / Runner - Signing & Capabilities). It allows more memory to be used / allocated.

Then rebuild, and it works as expected. I no longer get the memory warnings either. I hope this helps others!

![xcodeEntitlements](https://github.com/JaffaKetchup/flutter_map_tile_caching/assets/128325824/58e80b74-3a3b-4540-83fd-5ceaf5239a9a)

**Comment by JaffaKetchup** [comment] 2024-01-24 23:06
Ooo, that certainly is interesting. I don't have iOS devices to test on, so I haven't been able to look myself.
Huge thanks for finding that, I'll share it with the other issue.

If FMTC is an integral part of your app, please do consider donating! Any amount is greatly appreciated :D
