### ISSUE TITLE
[BUG] IsarError: The database is full.

### ISSUE THREAD

**Issue by stx** [JaffaKetchup/flutter_map_tile_caching#136] opened 2023-10-11 20:12 UTC
### What is the bug?

IsarError: The database is full.

Seen on 9.0.0-dev.3 on iOS 16.3.1 and Android 13 using production Sentry logs. No stacktraces passed.

Does this mean the user has loaded too many tiles? Or the disk is full? Or FMTC has hit some limit?

### How can we reproduce it?

Presumably seeing too many tiles? Or having a full disk?

Here's our implementation

```
    await FlutterMapTileCaching.initialise();

    StoreDirectory store = FMTC.instance('default');

    await store.manage.createAsync();

    // ...

    FMTC.instance('default').getTileProvider();
```

### Platforms

Android 13, iOS 16

### Severity

Fatal: Causes the application to crash

**Comment by JaffaKetchup** [comment] 2023-10-11 20:20
Hi @stx,

This means you've hit Isar's default storage limit. You can try setting a higher one in the initialise call, through the settings.

Remember that Isar works with virtual memory.

(If you're wondering about the state of this plugin right now, it's in a sort of limbo. I'm hoping to get back to it soon but I'm having some doubts about whether Isar is the correct tool for the job, and whether it is actively maintained enough. It's really great in terms of performance, but it's having some issues with stability.)

**Comment by JaffaKetchup** [comment] 2023-10-29 21:18
Just an update on how things are going, I've recently written this paragraph to a private user, that I'll share now:

> Unfortunately, we haven't heard from Simon, the Isar maintainer, in a couple of months, back when the last Isar prerelease was published.
> 
> This means that I'm worried about sticking with Isar. Isar is probably the most performant database available for Flutter (due to it's backend being written in Rust, which is coincidentally what causes issues (along with the MDBX database behing Isar) on iOS devices), particular when using more than one store. However, if it's not being maintained, I'm not 100% comfortable keeping it being FMTC, especially as it's causing many bugs. I have searched for alternatives, but I can't decide on one.
Additionally, one of my last remaining aims for v9 is to remove the duplicate of tiles between stores. However, making this performant is difficult now, as 'links' used for expressing relations have been removed from Isar, and alternative joined queries from composite indexes no longer seem to be available either - support for updating records is basic and essentially involves a query lookup, read and write operation for every browsed tile, which is three times as expensive as it is currently. This makes expressing a many-to-many relationship between tiles and stores difficult, especially while keeping it performant at a scale of hundreds of thousands of tiles. Import/export operations with the sharing plugin will also need to be rewritten and will become much slower. I'd be interested to know whether you are using this functionality?
> 
> Further compounding the slow development of FMTC recently is that I've started (the equivalent of) college in the last few months, and combined with the development on FM, I've been short on time. Hopefully I can start working more seriously on FMTC again now that FM v6 has been released (although there are more developments going on privately), and I have indeed made a few non-trivial commits to the example application of FMTC v9 within the past week.
>
> My recommendation would be to migrate to v9 now. It has awesome new functionality and performance enhancements, and very few bugs - along with a complete set of up-to-date documentation. FM v6 is also a huge step up.
One known bug is with the download recovery system, so you may wish to switch that off, along with the store recovery system if it's causing crashes.
I think that the API in the latest prerelease is unlikely to change significantly, even if I tear out the entire database. I think the most likely change is a change to what operations are sync/async. I would recommend however, pinning to the latest prerelease specifically, just so that there aren't any unforeseen issues.

Thank you all for sticking with FMTC through these issues, I'm hoping that they can be resolved soon! In fact, I'm writing to the maintainers over at ObjectBox to ask for clarification on a few things, and if that all goes well, the database rewriting will begin!

**Comment by JaffaKetchup** [comment] 2024-03-07 21:29
(@stx and others)

I'm pleased (and exhausted) to announce that the next (and hopefully final) prerelease is now available: https://pub.dev/packages/flutter_map_tile_caching/versions/9.0.0-dev.5. ObjectBox has finally arrived! A provisional CHANGELOG is available at https://pub.dev/packages/flutter_map_tile_caching/versions/9.0.0-dev.6/changelog#900---hundreds-of-hours---2024xxxx.

Some things to note:
* #148
* Importing functionality is not yet working
* There is no gurantee for stability in this version: I have done basic testing only
* There is little/no documentation available outside of what is in the code, including no migration info; I'll be happy to answer questions here, but some answers can be found in the CHANGELOG
* No data from older versions will be available, but the databases will not be modified/deleted - check your storage space if necessary

I'm really eager to hear feedback. The number one thing I want to hear is that there are no(!?) crashes! But I also want to hear about bugs you've found. At this point, I cannot take further feature requests: I cannot afford the time to expand the scope of this further at the moment.

Please post feedback in #105.

**Closed** 2024-04-11 11:24 UTC
Labels: bug, blocked, isar
