### ISSUE TITLE
[BUG] IsarError (IsarError: Cannot open Environment: MdbxError (12): Out of memory)

### ISSUE THREAD

**Issue by maotou316** [JaffaKetchup/flutter_map_tile_caching#138] opened 2023-10-23 01:36 UTC
### What is the bug?

Issue Description
I encountered an IsarError with the message Cannot open Environment: MdbxError (12): Out of memory while trying to initialize and create an instance using FMTC.

Code Snippet
Here's the code snippet where the issue occurs:

```
await FMTC.initialise(debugMode: true);
await FMTC.instance('mapStore').manage.createAsync();
```
Error Message
```
IsarError (IsarError: Cannot open Environment: MdbxError (12): Out of memory)
```

### How can we reproduce it?

Steps Taken to Resolve
Cleaned and rebuilt the project
Ensured all dependencies are up to date
None of these steps resolved the issue.

Additional Information
FMTC Version: (Please provide the version of FMTC you are using)
Isar Version: (Please provide the version of Isar you are using)
Flutter Version: (Please provide the version of Flutter you are using)
Operating Environment: (e.g., Android, iOS, Web)
Does anyone know how to resolve this issue? Thank you!

### Platforms

Pixel 7 API 29

### Severity

Obtrusive: Prevents normal functioning but causes no errors in the console

**Comment by JaffaKetchup** [comment] 2023-10-23 10:18
Duplicate of #105

**Closed by JaffaKetchup** 2023-10-23 10:18 UTC
Labels: bug, needs verification
