### ISSUE TITLE
[FEATURE] Bump package version isar 

### ISSUE THREAD

**Issue by bcanozter** [JaffaKetchup/flutter_map_tile_caching#120] opened 2023-04-28 19:51 UTC
### What do you want implemented?

Bump `isar` version from `3.0.6` to `3.1.0`. 

Note that this newer version comes with a breaking change. Mentioned to fix these https://github.com/isar/isar/issues/845 and https://github.com/isar/isar/issues/727 . 

### Platforms Affected

Android

### Severity

Obtrusive: No workarounds are available, and this is essential to me

### Requirements

- [X] I agree to follow this project's [Code of Conduct](https://github.com/jaffaketchup/flutter_map_tile_caching/blob/main/CODE_OF_CONDUCT.md)
- [X] I have checked for similar feature requests which may be duplicates
- [X] I am using the [latest stable version](https://pub.dev/packages/flutter_map_tile_caching) of this package
- [X] If I am using FMTC in a proprietary project, I have read and understood [this important legal notice](https://fmtc.jaffaketchup.dev/#proprietary-licensing)

**Comment by JaffaKetchup** [comment] 2023-04-28 19:57
Duplicate of https://github.com/JaffaKetchup/flutter_map_tile_caching/issues/117. Please see the Important Temporary Notice at the top of https://fmtc.jaffaketchup.dev/ for workarounds and resolutions.

**Closed by JaffaKetchup** 2023-04-28 19:57 UTC
Labels: enhancement

**Comment by JaffaKetchup** [comment] 2023-04-28 19:58
Duplicate of #117
