### ISSUE TITLE
IOS BUILD error Error: The method 'whereNotNull' isn't defined for the class 'Stream<MapEntry<int, Isar>?>'. [BUG] 

### ISSUE THREAD

**Issue by galizhan** [JaffaKetchup/flutter_map_tile_caching#141] opened 2023-11-24 11:26 UTC
### What is the bug?

Trying to build for IOS but this error came up 
`Error (Xcode): ../../.pub-cache/hosted/pub.dev/flutter_map_tile_caching-8.0.1/lib/src/db/registry.dart:178:14: Error: The method 'whereNotNull' isn't defined for the class 'Stream<MapEntry<int, Isar>?>'.

Could not build the application for the simulator.
Error launching application on iPhone 15.`

### How can we reproduce it?

here is part of my pubspec.yml
  flutter_map: ^4.0.0
  flutter_map_location_marker: ^6.0.0
  flutter_map_tile_caching: ^8.0.1

### Platforms

IOS

### Severity

Fatal: Causes the application to crash

**Comment by JaffaKetchup** [comment] 2023-11-24 11:41
Looks like this could be a duplicate of #93. Does the solution there work for you?
There's not a huge amount I can specifically do about this issue, as GitHub Actions correctly builds the app and pub.dev doesn't identify any issues.

**Comment by JaffaKetchup** [comment] 2023-11-24 12:11
Try https://stackoverflow.com/questions/74107738/parse-issue-xcode-module-path-provider-ios-not-found.
Note that these are all out of date because I'm working on v9 instead of trying to maintain v8. If you can switch to the latest version of FM, I would recommend using the available v9 prereleases.

**Closed** 2023-11-24 12:11 UTC
Labels: bug, duplicate, invalid

**Comment by galizhan** [comment] 2023-11-24 12:13
ok
